/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar1: [{
        type: 'autogenerated',
        dirName: 'cec1'
    }],
    tutorialSidebar: [{
        type: 'autogenerated',
        dirName: 'cec2'
    }],
    tutorialSidebar_cpc1: [{
        type: 'autogenerated',
        dirName: 'cpc1',
    }],

    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      {
        type: 'category',
        label: 'Tutorial',
        items: ['hello'],
      },
    ],
     */
};