import React from "react";
import clsx from "clsx";
import Layout from "@theme/Layout";
import Link from "@docusaurus/Link";
import useDocusaurusContext from "@docusaurus/useDocusaurusContext";
import styles from "./index.module.css";
import { useState, useEffect } from "react";
import bibtexParse from "bibtex-parse-js";
import { Paper } from "@mui/material";
// import { Cite } from 'citation-js';

const Cite = require("citation-js");

function PublicationsHeader() {
    const { siteConfig } = useDocusaurusContext();
    return (
        <header className={clsx("hero hero--primary", styles.heroBanner)}>
            <div className="container">
                <h1 className="hero__title"> The Cadenza Project </h1>{" "}
                <p className="hero__subtitle"> Publications </p>{" "}
                <div className={styles.buttons}> </div>{" "}
            </div>{" "}
        </header>
    );
}

// Renders a Google-Scholar-style badge, e.g.
// [46 Google Scholar citations] (linked to the Scholar citation page)
// citationInfo is looked up from static/citations.json by bib key.
const ScholarBadge = ({ citationInfo }) => {
    if (!citationInfo) return null;
    const { count, url } = citationInfo;
    const badgeSrc = `https://img.shields.io/badge/scholar-${count}-4285F4?logo=googlescholar&labelColor=beige`;
    const badgeImg = (
        <img
            src={badgeSrc}
            alt={`${count} Google Scholar citations`}
            style={{ verticalAlign: "middle" }}
        />
    );
    return (
        <div style={{ marginTop: "0.25rem" }}>
            {url ? <a href={url} target="_blank" rel="noreferrer">{badgeImg}</a> : badgeImg}
        </div>
    );
};

const renderCitation = (publication, citationsMap = {}) => {
    const url = publication.entryTags.url;
    publication.entryTags.url = "";
    publication.entryTags.doi = "";

    const citationString = bibtexParse.toBibtex([publication], false);
    const citation = new Cite(citationString);
    const formattedCitation = citation.format("bibliography", {
        format: "html",
        template: "apa",
        lang: "en-US",
    });

    const citationInfo = citationsMap?.[publication.citationKey];

    return (
        <div>
            <div dangerouslySetInnerHTML={{ __html: formattedCitation }} />
            {url && <a href={url}>{url}</a>}
            <ScholarBadge citationInfo={citationInfo} />
        </div>
    );
};

const PublicationsList = ({ year, citationsMap = {} }) => {
    const [publications, setPublications] = useState([]);

    useEffect(() => {
        fetch("publications.bib")
            .then((response) => response.text())
            .then((data) => {
                const parsedData = bibtexParse.toJSON(data);
                const filteredData = parsedData.filter(
                    (publication) => publication.entryTags.year === year.toString()
                );
                setPublications(filteredData);
            });
    }, [year]);

    return (
        <ul>
            {publications.map((publication, index) => (
                <li key={index}>{renderCitation(publication, citationsMap)}</li>
            ))}
        </ul>
    );
};

export default function Home() {
    const { siteConfig } = useDocusaurusContext();
    const [years, setYears] = useState([]);
    const [citationsMap, setCitationsMap] = useState({});

    useEffect(() => {
        fetch("publications.bib")
            .then((response) => response.text())
            .then((data) => {
                const parsedData = bibtexParse.toJSON(data);
                const uniqueYears = [
                    ...new Set(
                        parsedData.map((publication) => publication.entryTags.year)
                    ),
                ]
                    .sort()
                    .reverse();
                setYears(uniqueYears);
            });
    }, []);

    useEffect(() => {
        // citations.json is generated by scripts/fetch_scholar_citations.py
        // (run automatically via the GitHub Action). If it's missing, badges
        // simply won't render -- everything else still works.
        fetch("citations.json")
            .then((response) => (response.ok ? response.json() : {}))
            .catch(() => ({}))
            .then((data) => setCitationsMap(data || {}));
    }, []);

    return (
        <Layout
            title={`Hello from ${siteConfig.title}`}
            description="Description will go into a meta tag in <head />"
        >
            <main>
                <PublicationsHeader />
                <div className="container">
                    <Paper sx={{ p: 2, m: 4 }}>
                        {years.map((year) => (
                            <React.Fragment key={year}>
                                <h2>{year}</h2>
                                <PublicationsList year={year} citationsMap={citationsMap} />
                            </React.Fragment>
                        ))}
                    </Paper>
                </div>
            </main>{" "}
        </Layout>
    );
}